// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDulhrQZIkmDlPClX0tZI7_7VSfuRLhVRQ',
    appId: '1:821565225002:web:facf7dafeab374b9e96b53',
    messagingSenderId: '821565225002',
    projectId: 'customermanagement-b0b53',
    authDomain: 'customermanagement-b0b53.firebaseapp.com',
    storageBucket: 'customermanagement-b0b53.firebasestorage.app',
    measurementId: 'G-2WB8F97QKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xs7NExP1wR5WZ_gdc7zaGwShlAo9ZQ8',
    appId: '1:821565225002:android:211e6632cd9b3b88e96b53',
    messagingSenderId: '821565225002',
    projectId: 'customermanagement-b0b53',
    storageBucket: 'customermanagement-b0b53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqqTwz4o5aL6HkGRA21JpIfPaxJ6GW9I',
    appId: '1:821565225002:ios:92e8361de1e0fbbae96b53',
    messagingSenderId: '821565225002',
    projectId: 'customermanagement-b0b53',
    storageBucket: 'customermanagement-b0b53.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqqTwz4o5aL6HkGRA21JpIfPaxJ6GW9I',
    appId: '1:821565225002:ios:92e8361de1e0fbbae96b53',
    messagingSenderId: '821565225002',
    projectId: 'customermanagement-b0b53',
    storageBucket: 'customermanagement-b0b53.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDulhrQZIkmDlPClX0tZI7_7VSfuRLhVRQ',
    appId: '1:821565225002:web:c75ddaea48312d5ce96b53',
    messagingSenderId: '821565225002',
    projectId: 'customermanagement-b0b53',
    authDomain: 'customermanagement-b0b53.firebaseapp.com',
    storageBucket: 'customermanagement-b0b53.firebasestorage.app',
    measurementId: 'G-P5LXJ6Y9F3',
  );
}
